/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concs;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author lenovo
 */
public class his_ventas extends javax.swing.JFrame {
 
    // Instancias la clase que hemos creado anteriormente
     private Conect SQL = new Conect();
    // Llamas al método que tiene la clase y te devuelve una conexión
    private Connection conn = SQL.conectarMySQL();
    
    // Query que usarás para hacer lo que necesites
    private String sSQL =   "select id_cliente from venta";
    String datoCapturado = "";
    

   
    try {
        java.sql.Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery(sSQL);

        while (rs.next()) {
            datoCapturado = rs.getString("nombre");
        }
        if (datoCapturado.equals("")) {
            JOptionPane.showMessageDialog(null, "Usuario no registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Bienvenido");
            dispose();
            principal2 verMenu = new principal2();
            verMenu.setVisible(true);
        }
    } catch (SQLException ex) {
        Logger.getLogger(inicio_sesionn.class.getName()).log(Level.SEVERE, null, ex);
    }
           
    /**
     * Creates new form his_ventas
     */
    public his_ventas() {
        initComponents();
        pandatos.setBackground(new Color(255,255,255,220));
        //fondo
        ImageIcon imagen = new ImageIcon ("src/img/fondo.png");
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pandatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_registrar = new javax.swing.JButton();
        ta_salir = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pandatos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("HISTORIAL DE VENTAS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_producto", "Producto", "Vendedor", "Cantidad", "Total $", "Fecha", "Hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_registrar.setBackground(new java.awt.Color(23, 88, 144));
        btn_registrar.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("REGRESAR AL MENU");
        btn_registrar.setBorder(null);
        btn_registrar.setBorderPainted(false);
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pandatosLayout = new javax.swing.GroupLayout(pandatos);
        pandatos.setLayout(pandatosLayout);
        pandatosLayout.setHorizontalGroup(
            pandatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pandatosLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pandatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pandatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(322, 322, 322))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pandatosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pandatosLayout.createSequentialGroup()
                        .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))))
        );
        pandatosLayout.setVerticalGroup(
            pandatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pandatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pandatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 850, 510));

        ta_salir.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        ta_salir.setForeground(new java.awt.Color(75, 112, 135));
        ta_salir.setText("X");
        ta_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta_salirMouseExited(evt);
            }
        });
        jPanel1.add(ta_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
        btn_registrar.setBackground(new Color(116,144,179));
        btn_registrar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
        btn_registrar.setBackground(new Color(23,88,144));
        btn_registrar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_registrarMouseExited

    private void ta_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ta_salirMouseClicked

    private void ta_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseEntered
        ta_salir.setForeground(new Color(190,2,2));
    }//GEN-LAST:event_ta_salirMouseEntered

    private void ta_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseExited
        ta_salir.setForeground(new Color(75,112,135));
    }//GEN-LAST:event_ta_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(his_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(his_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(his_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(his_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new his_ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pandatos;
    private javax.swing.JLabel ta_salir;
    // End of variables declaration//GEN-END:variables
}
