/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concs;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author lenovo
 */
public class model_md extends javax.swing.JFrame {

    /**
     * Creates new form model_md
     */
    public model_md() {
        initComponents();
        pandatos.setBackground(new Color(255,255,255,220));
        //fondo
        ImageIcon imagen = new ImageIcon ("src/img/fondo.png");
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pandatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buq_marc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bsq_modelo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        auto = new javax.swing.JLabel();
        buq_marc1 = new javax.swing.JComboBox<>();
        btn_modificar = new javax.swing.JButton();
        btn_agregar1 = new javax.swing.JButton();
        ta_salir = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pandatos.setBackground(new java.awt.Color(255, 255, 255));
        pandatos.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("MODELOS");
        pandatos.add(jLabel1);
        jLabel1.setBounds(360, 21, 95, 23);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Marca:");
        pandatos.add(jLabel5);
        jLabel5.setBounds(50, 70, 95, 19);

        buq_marc.setBackground(new java.awt.Color(116, 144, 179));
        buq_marc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buq_marc.setForeground(new java.awt.Color(255, 255, 255));
        buq_marc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buq_marc.setBorder(null);
        pandatos.add(buq_marc);
        buq_marc.setBounds(430, 410, 300, 32);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Modelo:");
        pandatos.add(jLabel6);
        jLabel6.setBounds(280, 70, 95, 19);

        bsq_modelo.setBackground(new java.awt.Color(116, 144, 179));
        bsq_modelo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        bsq_modelo.setForeground(new java.awt.Color(255, 255, 255));
        bsq_modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bsq_modelo.setBorder(null);
        pandatos.add(bsq_modelo);
        bsq_modelo.setBounds(280, 90, 190, 32);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("País: ");
        pandatos.add(jLabel7);
        jLabel7.setBounds(50, 170, 34, 19);

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(jTextField1);
        jTextField1.setBounds(100, 160, 300, 28);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Marca: ");
        pandatos.add(jLabel8);
        jLabel8.setBounds(50, 210, 52, 19);

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(jTextField2);
        jTextField2.setBounds(130, 200, 270, 28);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Modelo: ");
        pandatos.add(jLabel9);
        jLabel9.setBounds(50, 250, 61, 19);

        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(jTextField3);
        jTextField3.setBounds(130, 240, 270, 28);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Precio:   $");
        pandatos.add(jLabel10);
        jLabel10.setBounds(50, 290, 67, 19);

        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(jTextField4);
        jTextField4.setBounds(130, 290, 270, 28);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Características: ");
        pandatos.add(jLabel11);
        jLabel11.setBounds(50, 330, 108, 19);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        pandatos.add(jScrollPane1);
        jScrollPane1.setBounds(50, 360, 350, 80);

        auto.setText("imagenes");
        auto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pandatos.add(auto);
        auto.setBounds(430, 160, 300, 250);

        buq_marc1.setBackground(new java.awt.Color(116, 144, 179));
        buq_marc1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buq_marc1.setForeground(new java.awt.Color(255, 255, 255));
        buq_marc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buq_marc1.setBorder(null);
        pandatos.add(buq_marc1);
        buq_marc1.setBounds(50, 100, 190, 32);

        btn_modificar.setBackground(new java.awt.Color(23, 88, 144));
        btn_modificar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("MODIFICAR");
        btn_modificar.setBorder(null);
        btn_modificar.setBorderPainted(false);
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificarMouseExited(evt);
            }
        });
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        pandatos.add(btn_modificar);
        btn_modificar.setBounds(320, 470, 170, 30);

        btn_agregar1.setBackground(new java.awt.Color(23, 88, 144));
        btn_agregar1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_agregar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar1.setText("AGREGAR");
        btn_agregar1.setBorder(null);
        btn_agregar1.setBorderPainted(false);
        btn_agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregar1MouseExited(evt);
            }
        });
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });
        pandatos.add(btn_agregar1);
        btn_agregar1.setBounds(130, 470, 170, 30);

        jPanel1.add(pandatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 760, 530));

        ta_salir.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        ta_salir.setForeground(new java.awt.Color(75, 112, 135));
        ta_salir.setText("X");
        ta_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta_salirMouseExited(evt);
            }
        });
        jPanel1.add(ta_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 20, 20));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseEntered
        btn_modificar.setBackground(new Color(116,144,179));
        btn_modificar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btn_modificarMouseEntered

    private void btn_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseExited
        btn_modificar.setBackground(new Color(23,88,144));
        btn_modificar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_modificarMouseExited

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        /*pago fin = new pago();
        fin.setLocationRelativeTo(null);
        fin.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void ta_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ta_salirMouseClicked

    private void ta_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseEntered
        ta_salir.setForeground(new Color(190,2,2));
    }//GEN-LAST:event_ta_salirMouseEntered

    private void ta_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseExited
        ta_salir.setForeground(new Color(75,112,135));
    }//GEN-LAST:event_ta_salirMouseExited

    private void btn_agregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1MouseEntered

    private void btn_agregar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1MouseExited

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(model_md.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(model_md.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(model_md.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(model_md.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new model_md().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auto;
    private javax.swing.JComboBox<String> bsq_modelo;
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> buq_marc;
    private javax.swing.JComboBox<String> buq_marc1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel pandatos;
    private javax.swing.JLabel ta_salir;
    // End of variables declaration//GEN-END:variables
}
