/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concs;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author lenovo
 */
public class modelo extends javax.swing.JFrame {
   Conect con = new Conect();
    Connection conexion = con.Conexion();
    

    /**
     * Creates new form modelo
     */
    public modelo() {
        initComponents();
        
        pandatos.setBackground(new Color(255,255,255,220));
        //fondo
        ImageIcon imagen = new ImageIcon ("src/img/fondo.png");
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
        con.obtener_ruta();
         String sql = "";
        
    sql = "SELECT nombre FROM marca";
    CBmarca.removeAllItems();
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            String id = rs.getString("nombre");
            CBmarca.addItem(id);
        }
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pandatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CBimagenes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CBmodelo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txpais = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txmarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txmodelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txprecio = new javax.swing.JTextField();
        auto = new javax.swing.JLabel();
        CBmarca = new javax.swing.JComboBox<>();
        btn_pagar = new javax.swing.JButton();
        ta_salir = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pandatos.setBackground(new java.awt.Color(255, 255, 255));
        pandatos.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("MODELOS");
        pandatos.add(jLabel1);
        jLabel1.setBounds(460, 20, 95, 23);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Marca:");
        pandatos.add(jLabel5);
        jLabel5.setBounds(50, 70, 95, 19);

        CBimagenes.setBackground(new java.awt.Color(116, 144, 179));
        CBimagenes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CBimagenes.setForeground(new java.awt.Color(255, 255, 255));
        CBimagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exterior", "Interior", "Motor" }));
        CBimagenes.setBorder(null);
        CBimagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBimagenesActionPerformed(evt);
            }
        });
        pandatos.add(CBimagenes);
        CBimagenes.setBounds(510, 390, 300, 32);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Modelo:");
        pandatos.add(jLabel6);
        jLabel6.setBounds(280, 70, 95, 19);

        CBmodelo.setBackground(new java.awt.Color(116, 144, 179));
        CBmodelo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CBmodelo.setForeground(new java.awt.Color(255, 255, 255));
        CBmodelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBmodelo.setBorder(null);
        CBmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmodeloActionPerformed(evt);
            }
        });
        pandatos.add(CBmodelo);
        CBmodelo.setBounds(280, 100, 190, 32);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("País: ");
        pandatos.add(jLabel7);
        jLabel7.setBounds(50, 220, 34, 19);

        txpais.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(txpais);
        txpais.setBounds(130, 210, 300, 28);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Marca: ");
        pandatos.add(jLabel8);
        jLabel8.setBounds(50, 260, 52, 19);

        txmarca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(txmarca);
        txmarca.setBounds(130, 250, 300, 28);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Modelo: ");
        pandatos.add(jLabel9);
        jLabel9.setBounds(50, 300, 61, 19);

        txmodelo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(txmodelo);
        txmodelo.setBounds(130, 290, 300, 28);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Precio:   $");
        pandatos.add(jLabel10);
        jLabel10.setBounds(50, 340, 67, 19);

        txprecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandatos.add(txprecio);
        txprecio.setBounds(130, 340, 300, 28);

        auto.setText("imagenes");
        auto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pandatos.add(auto);
        auto.setBounds(510, 90, 450, 290);

        CBmarca.setBackground(new java.awt.Color(116, 144, 179));
        CBmarca.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CBmarca.setForeground(new java.awt.Color(255, 255, 255));
        CBmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBmarca.setBorder(null);
        CBmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmarcaActionPerformed(evt);
            }
        });
        pandatos.add(CBmarca);
        CBmarca.setBounds(50, 100, 190, 32);

        btn_pagar.setBackground(new java.awt.Color(23, 88, 144));
        btn_pagar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_pagar.setForeground(new java.awt.Color(255, 255, 255));
        btn_pagar.setText("Hacer compra");
        btn_pagar.setBorder(null);
        btn_pagar.setBorderPainted(false);
        btn_pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pagarMouseExited(evt);
            }
        });
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });
        pandatos.add(btn_pagar);
        btn_pagar.setBounds(300, 480, 170, 30);

        jPanel1.add(pandatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 980, 530));

        ta_salir.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        ta_salir.setForeground(new java.awt.Color(75, 112, 135));
        ta_salir.setText("X");
        ta_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta_salirMouseExited(evt);
            }
        });
        jPanel1.add(ta_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 20, 20));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagarMouseEntered
        btn_pagar.setBackground(new Color(116,144,179));
        btn_pagar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btn_pagarMouseEntered

    private void btn_pagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagarMouseExited
        btn_pagar.setBackground(new Color(23,88,144));
        btn_pagar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_pagarMouseExited

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        /*pago fin = new pago();
        fin.setLocationRelativeTo(null);
        fin.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_btn_pagarActionPerformed

    private void ta_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ta_salirMouseClicked

    private void ta_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseEntered
        ta_salir.setForeground(new Color(190,2,2));
    }//GEN-LAST:event_ta_salirMouseEntered

    private void ta_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_salirMouseExited
        ta_salir.setForeground(new Color(75,112,135));
    }//GEN-LAST:event_ta_salirMouseExited

    private void CBmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmarcaActionPerformed
        System.out.println("seleccionaste "+CBmarca.getSelectedItem());
        String sql1 = "";
        sql1 = "SELECT automovil.nombre FROM marca, automovil where automovil.id_marca=marca.id_marca and marca.nombre='"+CBmarca.getSelectedItem()+"'";
    CBmodelo.removeAllItems();
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql1);
        while(rs.next()){
            String id = rs.getString("nombre");
            CBmodelo.addItem(id);
        }
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    }//GEN-LAST:event_CBmarcaActionPerformed

    private void CBmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmodeloActionPerformed
        System.out.println("seleccionaste "+CBmodelo.getSelectedItem());
        String sql1 = "";
        sql1 = "SELECT pais.nombre FROM pais, marca where pais.id_pais=marca.id_pais and marca.nombre='"+CBmarca.getSelectedItem()+"'";
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    while(rs.next()){
            String id = rs.getString("nombre");
            txpais.setText(id);
        }
        
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    
    
     
        sql1 = "SELECT precio FROM automovil where nombre='"+CBmodelo.getSelectedItem()+"'";
   
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql1);
        while(rs.next()){
            String id = rs.getString("precio");
            txprecio.setText(id);
            System.out.println("");
        }
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    
    
    
    CBimagenes.setEnabled(true);
    String ma = CBmarca.getSelectedItem()+"";
    String mo = CBmodelo.getSelectedItem()+"";
        txmarca.setText(ma);
        if(CBmodelo.getSelectedItem()==null){
          txmodelo.setText("No hay modelos en existencia");  
          txprecio.setText("");
          CBimagenes.setEnabled(false);
        }else{
            txmodelo.setText(mo);
        }
        
    }//GEN-LAST:event_CBmodeloActionPerformed

    private void CBimagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBimagenesActionPerformed
       int sel= CBimagenes.getSelectedIndex();
        System.out.println("selecccionaste " +sel);
        String ext ="";
        String in ="";
        String mo ="";
        String sql1 = "";
        sql1 = "SELECT I_exterior, I_interior, I_motor FROM automovil where nombre='"+CBmodelo.getSelectedItem()+"'";
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    while(rs.next()){
            ext= rs.getString("I_exterior");
            in = rs.getString("I_interior");
            mo = rs.getString("I_motor");
            
        }
        
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    
        con.obtener_ruta();
        String h = con.ruta_mera;
    
        if(sel==0){
            System.out.println("Tu imagen es: "+ext);
            
            String rutimg =h+"\\consecionario\\"+ext;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
        }
        if(sel==1){
            System.out.println("Tu imagen es: "+in);
            
            String rutimg =h+"\\consecionario\\"+in;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
        }
        if(sel==2){
            System.out.println("Tu imagen es: "+mo);

            String rutimg =h+"\\consecionario\\"+mo;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
        }
        
    }//GEN-LAST:event_CBimagenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBimagenes;
    private javax.swing.JComboBox<String> CBmarca;
    private javax.swing.JComboBox<String> CBmodelo;
    private javax.swing.JLabel auto;
    private javax.swing.JButton btn_pagar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pandatos;
    private javax.swing.JLabel ta_salir;
    private javax.swing.JTextField txmarca;
    private javax.swing.JTextField txmodelo;
    private javax.swing.JTextField txpais;
    private javax.swing.JTextField txprecio;
    // End of variables declaration//GEN-END:variables
}
