/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concs;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author lenovo
 */
public class new_p extends javax.swing.JFrame {

     Conect con = new Conect();
    Connection conexion = con.Conexion();
    public int VIE=0;
    public int VII=0;
    public int VIM=0;
    
    public int sel=4;
    
    
    public String nEx=null;
    public String nIn=null;
    public String nMo=null;
    
    public int convert=0;
    
    public void id(){
        String sql = "";
        //obtecion de ultimo id para generar siguiente id y evitar repeticiones y posibles errores
        String id_="";
    sql = "SELECT * FROM automovil";
    
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            String id = rs.getString("id_auto");
            id_=id;
        }
        int conver = Integer.parseInt(id_);
        convert=conver+1;
        //System.out.println(convert+"  "+ conver);
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    }
    /**
     * Creates new form new_p
     */
    public new_p() {
        initComponents();
        pandato.setBackground(new Color(255,255,255,220));
        //fondo
        ImageIcon imagen = new ImageIcon ("src/img/fondo.png");
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
        String sql = "";
        
         sql = "SELECT nombre FROM marca";
    CBmarca.removeAllItems();
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            String id = rs.getString("nombre");
            CBmarca.addItem(id);
        }
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
    
     id();
    
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pandato = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CBmarca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TXpais = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXmodelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXprecio = new javax.swing.JTextField();
        auto = new javax.swing.JLabel();
        CBimagenes = new javax.swing.JComboBox<>();
        BTagregar = new javax.swing.JButton();
        btn_agregar1 = new javax.swing.JButton();
        TXmarca = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pandato.setBackground(new java.awt.Color(255, 255, 255));
        pandato.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("AGREGAR NUEVO VEHICULO");
        pandato.add(jLabel1);
        jLabel1.setBounds(350, 20, 260, 23);

        btn_agregar.setBackground(new java.awt.Color(23, 88, 144));
        btn_agregar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Cancelar");
        btn_agregar.setBorder(null);
        btn_agregar.setBorderPainted(false);
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregarMouseExited(evt);
            }
        });
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        pandato.add(btn_agregar);
        btn_agregar.setBounds(160, 470, 149, 31);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Elige la marca");
        pandato.add(jLabel7);
        jLabel7.setBounds(100, 70, 160, 19);

        CBmarca.setBackground(new java.awt.Color(116, 144, 179));
        CBmarca.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CBmarca.setForeground(new java.awt.Color(255, 255, 255));
        CBmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBmarca.setBorder(null);
        CBmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmarcaActionPerformed(evt);
            }
        });
        pandato.add(CBmarca);
        CBmarca.setBounds(100, 100, 270, 32);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Marca: ");
        pandato.add(jLabel8);
        jLabel8.setBounds(40, 270, 52, 19);

        TXpais.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        TXpais.setEnabled(false);
        pandato.add(TXpais);
        TXpais.setBounds(110, 220, 270, 28);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Modelo: ");
        pandato.add(jLabel9);
        jLabel9.setBounds(30, 310, 61, 19);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("País: ");
        pandato.add(jLabel10);
        jLabel10.setBounds(50, 230, 34, 19);

        TXmodelo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandato.add(TXmodelo);
        TXmodelo.setBounds(110, 300, 270, 28);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Precio:   $");
        pandato.add(jLabel11);
        jLabel11.setBounds(40, 350, 67, 19);

        TXprecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        pandato.add(TXprecio);
        TXprecio.setBounds(110, 350, 270, 28);

        auto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        auto.setText("        No has elegido una imagen del Exterior");
        auto.setToolTipText("");
        auto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pandato.add(auto);
        auto.setBounds(450, 80, 450, 280);

        CBimagenes.setBackground(new java.awt.Color(116, 144, 179));
        CBimagenes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CBimagenes.setForeground(new java.awt.Color(255, 255, 255));
        CBimagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exterior", "Interior", "Motor" }));
        CBimagenes.setBorder(null);
        CBimagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBimagenesActionPerformed(evt);
            }
        });
        pandato.add(CBimagenes);
        CBimagenes.setBounds(520, 370, 300, 32);

        BTagregar.setText("Elegir imagen del Exterior");
        BTagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTagregarActionPerformed(evt);
            }
        });
        pandato.add(BTagregar);
        BTagregar.setBounds(530, 410, 270, 23);

        btn_agregar1.setBackground(new java.awt.Color(23, 88, 144));
        btn_agregar1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_agregar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar1.setText("Agregar");
        btn_agregar1.setBorder(null);
        btn_agregar1.setBorderPainted(false);
        btn_agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregar1MouseExited(evt);
            }
        });
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });
        pandato.add(btn_agregar1);
        btn_agregar1.setBounds(600, 470, 149, 31);

        TXmarca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(116, 144, 179)));
        TXmarca.setEnabled(false);
        pandato.add(TXmarca);
        TXmarca.setBounds(110, 260, 270, 28);

        jPanel1.add(pandato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 920, 540));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 970, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseEntered
        btn_agregar.setBackground(new Color(116,144,179));
        btn_agregar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btn_agregarMouseEntered

    private void btn_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseExited
        btn_agregar.setBackground(new Color(23,88,144));
        btn_agregar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_agregarMouseExited

    private void CBimagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBimagenesActionPerformed
        sel= CBimagenes.getSelectedIndex();
        con.obtener_ruta();
        String h = con.ruta_mera;
    
        if(sel==0){
            BTagregar.setText("Elegir imagen del Exterior");
            if(VIE==0){
                auto.setText("        No has elegido una imagen del Exterior");
                auto.setIcon(null);
            }else{
                String rutimg =con.ruta_mera+"\\consecionario\\"+nEx;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
            }
            
        }
        if(sel==1){
            BTagregar.setText("Elegir imagen del Interior");
            if(VII==0){
                auto.setText("        No has elegido una imagen del Interior");
                auto.setIcon(null);
            }else{
                String rutimg =con.ruta_mera+"\\consecionario\\"+nIn;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
            }
            
        }
        if(sel==2){
           BTagregar.setText("Elegir imagen del Motor");
           if(VIM==0){
               auto.setText("        No has elegido una imagen del Motor");
               auto.setIcon(null);
           }else{
               String rutimg =con.ruta_mera+"\\consecionario\\"+nMo;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
           }
           
        }
        
        
    }//GEN-LAST:event_CBimagenesActionPerformed

    private void BTagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTagregarActionPerformed

        if(sel==0){
        nEx=convert+"_E.png";
        con.elegir_imagen(nEx);
        
        String rutimg =con.ruta_mera+"\\consecionario\\"+nEx;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
        VIE=1;
        }
        if(sel==1){
        nIn=convert+"_I.png";
        con.elegir_imagen(nIn);
        
        String rutimg =con.ruta_mera+"\\consecionario\\"+nIn;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
        VII=1;
        }
        if(sel==2){
        nMo=convert+"_M.png";
        con.elegir_imagen(nMo);
        
        String rutimg =con.ruta_mera+"\\consecionario\\"+nMo;
            System.out.println("Ruta final "+rutimg);
            ImageIcon imagen = new ImageIcon (rutimg);
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(auto.getWidth(),auto.getHeight(),Image.SCALE_DEFAULT));
        auto.setIcon(icono);
        this.repaint();
        VIM=1;
        }
    }//GEN-LAST:event_BTagregarActionPerformed

    private void btn_agregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1MouseEntered

    private void btn_agregar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1MouseExited

    private void CBmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmarcaActionPerformed
      String sql1 = "";
        sql1 = "SELECT pais.nombre FROM pais, marca where pais.id_pais=marca.id_pais and marca.nombre='"+CBmarca.getSelectedItem()+"'";
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    while(rs.next()){
            String id = rs.getString("nombre");
            TXpais.setText(id);
        }
        String ma = CBmarca.getSelectedItem()+"";
        TXmarca.setText(ma);
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
        
        
    }//GEN-LAST:event_CBmarcaActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       con.borrar_img(nEx);
       nEx=null;
       con.borrar_img(nIn);
       nIn=null;
       con.borrar_img(nMo);
       nMo=null;
       VIE=0;
       VII=0;
       VIM=0;
       auto.setIcon(null);
       
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed
        String sql1 = "";
        String concert="";
        sql1 = "SELECT * FROM marca where nombre='"+CBmarca.getSelectedItem()+"'";
    try{
        Statement st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    while(rs.next()){
            String id = rs.getString("id_marca");
            concert=id;
        }
        
        
    }catch(SQLException ex){
        System.out.println("No se pudo consultar la informacion");
    }
        
        
        if(nEx==null){
            JOptionPane.showMessageDialog(null, "Falta añadir la imagen del exterior", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{if(nIn==null){
             JOptionPane.showMessageDialog(null, "Falta añadir la imagen del interior", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{if(nMo==null){
             JOptionPane.showMessageDialog(null, "Falta añadir la imagen del motor", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{if("".equals(TXmodelo.getText())){
             JOptionPane.showMessageDialog(null, "Falta añadir el nombre del modelo", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{if("".equals(TXprecio.getText())){
             JOptionPane.showMessageDialog(null, "Falta añadir el precio del automovil", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
             try {
           
           

            // Obtener el nuevo id_auto
            int nuevoId = convert;
            int id_marca1 = Integer.parseInt(concert);

            // Datos a insertar en la tabla
            String nombre = TXmodelo.getText();
            int marca = id_marca1;
            String i_exterior = nEx;
            String i_interior = nIn;
            String i_motor = nMo;
            int precio = Integer.parseInt(TXprecio.getText());

            // Consulta SQL para la inserción
            String consultaSQL = "INSERT INTO automovil (id_auto, nombre, id_marca, I_exterior, I_interior, I_motor, precio) VALUES (?, ?, ?, ?, ?, ?,?)";

            // Crear una declaración preparada
            PreparedStatement preparedStatement = conexion.prepareStatement(consultaSQL);

            // Establecer valores para los parámetros de la consulta
            preparedStatement.setInt(1, nuevoId);
            preparedStatement.setString(2, nombre);
            preparedStatement.setInt(3, marca);
            preparedStatement.setString(4, i_exterior);
            preparedStatement.setString(5, i_interior);
            preparedStatement.setString(6, i_motor);
            preparedStatement.setInt(7, precio);

            // Ejecutar la consulta de inserción
            int filasAfectadas = preparedStatement.executeUpdate();

            if (filasAfectadas > 0) {
                System.out.println("Nuevo automóvil insertado con éxito.");
            } else {
                System.out.println("No se pudo insertar el nuevo automóvil.");
            }

            

        } catch (SQLException e) {
            e.printStackTrace();
        
        }
            
            
       nEx=null;
       nIn=null;
       nMo=null;
       VIE=0;
       VII=0;
       VIM=0;
       auto.setIcon(null);
       TXprecio.setText("");
       TXmodelo.setText("");
       id();
        }   
            
        }
            
        }
            
        }
            
        }
            
        
       
    }//GEN-LAST:event_btn_agregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_p().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTagregar;
    private javax.swing.JComboBox<String> CBimagenes;
    private javax.swing.JComboBox<String> CBmarca;
    private javax.swing.JTextField TXmarca;
    private javax.swing.JTextField TXmodelo;
    private javax.swing.JTextField TXpais;
    private javax.swing.JTextField TXprecio;
    private javax.swing.JLabel auto;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pandato;
    // End of variables declaration//GEN-END:variables
}
